version: '3.3'
services:
  collabora:
    image: collabora/code
    container_name: collabora_app
    networks:
      - proxy
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - domain: nextcloud.example.com #PUT IN THE LINK OF YOUR NEXTCLOUD
      - username: USER                #DEFINE USERNAME
      - password: PWD                 #DEFINE PASSWORD
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.entrypoints=http"
      - "traefik.http.routers.collabora.rule=Host(`collabora.example.com`)"  #CHANGE URL
      - "traefik.http.middlewares.collabora-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.collabora.middlewares=collabora-https-redirect"
      - "traefik.http.routers.collabora-secure.entrypoints=https"
      - "traefik.http.routers.collabora-secure.rule=Host(`collabora.example.com`)"  #CHANGE URL
      - "traefik.http.routers.collabora-secure.tls=true"
      - "traefik.http.routers.collabora-secure.tls.certresolver=http"
      - "traefik.http.routers.collabora-secure.service=collabora"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.collabora-secure.middlewares=secHeaders@file"
networks:
  proxy:
    external: true